[package]
license.workspace = true
readme.workspace = true
repository.workspace = true
name = "er"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
description = "Er, errors with less r"
keywords = ["error", "error-handling", "context", "report", "no_std"]
categories = ["rust-patterns", "no-std"]

[lib]
doctest = false

[features]
default = ["src_locations", "macros"]
src_locations = []
stack_traces = []
small_path_src = []
macros = ["dep:er-macros"]
lazy = []
test = []
serde = ["dep:serde"]

[dependencies]
er-macros = { version = "=0.3.0", path = "../er-macros", optional = true }
serde = { workspace = true, optional = true }

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true

[[example]]
name = "context"
path = "runnable_examples/context.rs"
required-features = ["macros"]
