[package]
license.workspace = true
readme = "README.md"
repository.workspace = true
name = "er-unsync"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
description = "Er with Rc sharing and errors without Send/Sync requirements"
keywords = ["error", "error-handling", "context", "report", "no_std"]
categories = ["rust-patterns", "no-std"]

[lib]
path = "../er/src/lib.rs"
doctest = false

[features]
default = ["src_locations", "macros", "test"]
src_locations = []
stack_traces = []
small_path_src = []
macros = ["dep:er-macros"]
lazy = []
test = []
serde = ["dep:serde"]

[dependencies]
er-macros = { version = "=0.7.1", path = "../er-macros", optional = true }
serde = { workspace = true, optional = true }

[lints]
workspace = true
